let board = document.querySelector(".board");
let adjustments = document.querySelector(".adjustments");
let length = 16;
let colorPicker = document.createElement("input");
colorPicker.setAttribute("type", "color");
let eraser = document.createElement("button");
eraser.textContent = "Eraser";
let rainbow = document.createElement("button");
rainbow.textContent = "Rainbow";
let shading = document.createElement("button");
shading.textContent = "Shading";
let clear = document.createElement("button");
clear.textContent = "Clear";
let slider = document.createElement("input");
slider.setAttribute("type", "range");
slider.setAttribute("min", 3);
slider.setAttribute("max", 100);
slider.setAttribute("value", length);
let grid = document.createElement("button");
grid.textContent = "Grid Lines";

adjustments.appendChild(colorPicker);
adjustments.appendChild(eraser);
adjustments.appendChild(rainbow);
adjustments.appendChild(shading);
adjustments.appendChild(clear);
adjustments.appendChild(slider);
adjustments.appendChild(grid);
